name: Build and publish
on:
  push:
    branches:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup rust targets
        run: |
          rustup target add armv7-linux-androideabi
          rustup target add aarch64-linux-android

      - uses: gradle/gradle-build-action@v2
      - run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
